/**
 * Evidence authority model (Task 4).
 *
 * How a memory claim traces to its source: user note, verified Study
 * finding, Performance evidence, Analysis evidence, Search session, or
 * another source kind. Authority is structural, NOT textual: a summary
 * generated by an agent cannot become authoritative solely because it is
 * fluent. Agent-produced provenance is capped, and "observed" claims must
 * trace to real evidence references.
 */
import type {
  AuthorityAssessment,
  AuthorityTier,
  EpistemicClass,
  SourceKind,
} from "../contracts/types.ts";
import { ValidationError } from "../contracts/errors.ts";

export const SOURCE_KINDS: readonly SourceKind[] = [
  "user_note",
  "user_decision",
  "study_finding",
  "performance_evidence",
  "analysis_evidence",
  "search_session",
  "repository_evidence",
  "external_document",
  "agent_summary",
  "agent_inference",
  "unknown",
];

/** Base authority tier for each source kind. */
export const SOURCE_KIND_TIER: Record<SourceKind, AuthorityTier> = {
  user_note: "user_reported",
  // An explicit user-authored decision within its declared scope is the user's
  // strongest SUBJECTIVE authority — above a general note, below verified
  // external evidence (Task 32).
  user_decision: "user_decision",
  study_finding: "verified_source",
  performance_evidence: "verified_source",
  analysis_evidence: "analysis",
  search_session: "analysis",
  repository_evidence: "verified_source",
  external_document: "analysis",
  agent_summary: "agent_derived",
  agent_inference: "agent_derived",
  unknown: "unattributed",
};

/** Kinds produced by agent derivation — structurally capped. */
const AGENT_DERIVED_KINDS: ReadonlySet<string> = new Set([
  "agent_summary",
  "agent_inference",
]);

/**
 * Authority assessment for a record. Deterministic function of provenance
 * and epistemic class; never a function of content fluency.
 */
export function authorityOf(
  provenance: { sourceKind: SourceKind },
  epistemicClass: EpistemicClass,
): AuthorityAssessment {
  const tier = SOURCE_KIND_TIER[provenance.sourceKind] ?? "unattributed";
  const capReasons: string[] = [];
  let capped = false;
  if (AGENT_DERIVED_KINDS.has(provenance.sourceKind)) {
    capped = true;
    capReasons.push(
      `sourceKind '${provenance.sourceKind}' is agent-derived: capped to 'agent_derived' regardless of epistemic class`,
    );
  }
  if (provenance.sourceKind === "unknown") {
    capped = true;
    capReasons.push("sourceKind is 'unknown': capped to 'unattributed'");
  }
  if (epistemicClass === "inferred" || epistemicClass === "recommendation") {
    capped = true;
    capReasons.push(
      `epistemicClass '${epistemicClass}': claim is inference/recommendation, not verified truth`,
    );
  }
  const basis =
    provenance.sourceKind === "unknown"
      ? "no attributable source kind"
      : `traces to '${provenance.sourceKind}'`;
  return { tier, basis, capped, capReasons };
}

/**
 * Structural authority rules enforced at write time (before persistence):
 *
 * 1. `observed` requires at least one evidence reference — observation
 *    means the claim traces to source evidence, not to narration.
 * 2. `observed` requires a non-agent, non-unknown source kind — agent
 *    output can be summarized/inferred, never claimed as observation.
 * 3. `agent_summary` requires `derivedFrom` — a summary must point at what
 *    it summarizes, or it is unattributed agent output.
 */
export function validateAuthority(input: {
  epistemicClass: EpistemicClass;
  evidenceRefCount: number;
  sourceKind: SourceKind;
  hasDerivedFrom: boolean;
}): void {
  if (input.epistemicClass === "observed") {
    if (input.evidenceRefCount === 0) {
      throw new ValidationError(
        "epistemicClass 'observed' requires at least one evidenceRefs entry (observed claims must trace to source evidence)",
      );
    }
    if (AGENT_DERIVED_KINDS.has(input.sourceKind)) {
      throw new ValidationError(
        `epistemicClass 'observed' cannot be grounded by agent-derived sourceKind '${input.sourceKind}': agent summaries are never authoritative as observations`,
      );
    }
    if (input.sourceKind === "unknown") {
      throw new ValidationError(
        "epistemicClass 'observed' requires an explicit sourceKind (not 'unknown')",
      );
    }
  }
  if (input.sourceKind === "agent_summary" && !input.hasDerivedFrom) {
    throw new ValidationError(
      "sourceKind 'agent_summary' requires provenance.derivedFrom pointing at the summarized source",
    );
  }
}

export function validateSourceKind(value: unknown): SourceKind {
  if (typeof value !== "string" || !SOURCE_KINDS.includes(value as SourceKind)) {
    throw new ValidationError(
      `sourceKind must be one of ${SOURCE_KINDS.join(", ")}`,
    );
  }
  return value as SourceKind;
}
